import { Box, OrbitControls } from "@react-three/drei";
import { Canvas, useStore } from "@react-three/fiber";
import { styled } from "@stitches/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { Suspense, useEffect, useRef } from "react";
import { PanelLegend, Interface, Text, Button, Panel } from "../components/hud";
import styles from "../styles/Home.module.css";
import Effects from "../components/Effects";
import Ribbon from "../components/Ribbon";
import { useSpring, animated } from "@react-spring/three";

const Main = styled("main", {
  width: "100vw",
  height: "100vh",
});

const Overlay = styled("div", {
  position: "absolute",
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  color: "white",
  maxWidth: "480px",
});

const OverlaySmall = styled("div", {
  position: "fixed",
  right: 0,
  bottom: "165px",
  color: "white",
  width: "480px",
});

const RandomRotateGroup = ({ children }: { children: any }) => {
  return <group>{children}</group>;
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Canvas
          style={{ position: "fixed" }}
          camera={{ position: [15, 15, 15] }}
        >
          <color attach="background" args={["black"]} />
          {/* <Sky azimuth={1} inclination={0.1} distance={1000} /> */}
          <ambientLight intensity={0.1} />
          <pointLight position={[10, 10, 10]} />
          <Suspense fallback={null}>
            <pointLight position={[30, 0, 0]} color="blue" intensity={10} />
            <RandomRotateGroup>
              <Ribbon id={1} color="#7b505c" />
              <Ribbon id={64} color="#E8AE3B" />
              <Ribbon id={256} color="#E8AE3B" />
              <Ribbon id={512} color="#E8AE3B" />
              <Ribbon id={128} color="#e4d6cf" />
            </RandomRotateGroup>
            <Effects />
          </Suspense>
          <OrbitControls
            minPolarAngle={Math.PI / 10}
            maxPolarAngle={Math.PI / 1.5}
          />
        </Canvas>
      </Main>

      <Overlay>
        <Interface>
          <Panel>
            <PanelLegend>Welcome</PanelLegend>
            <Text>Hi, I’m Ben</Text>
            <br />

            <Text>
              I&apos;m a UI Engineer, designer, generative artist and
              independent game developer living in Brisbane, Australia.
            </Text>
            <br />

            <Text>
              I make powerful, intuitive and joyful software using the tools I
              love.
            </Text>
            {/* <br /> */}

            {/* <Text>
              You&apos;ll find me working at the intersection of art,
              technology, psychology, philosophy and human connection.
            </Text> */}
          </Panel>
          <Panel>
            <PanelLegend>Social</PanelLegend>
            <Button>
              <code>[T]</code> twitter
            </Button>
            <br />
            <Button>
              <code>[G]</code> github
            </Button>
            <br />
            <Button>
              <code>[W]</code> twitch
            </Button>
            <br />
            <Button>
              <code>[A]</code> are.na
            </Button>
            <br />
            <Button>
              <code>[I]</code> itch.io
            </Button>
            <br />
          </Panel>
          <Panel>
            <PanelLegend>Work</PanelLegend>
            <Text>
              I will be open for freelance and contract work early 2022.
            </Text>
            <br />
            <Text>
              {" "}
              I have extensive exprience with UI/UX engineering, design systems,
              gamedev, interactive visuals (webgl &amp; canvas) and mentoring
              enthusiastic developers.
            </Text>
            <br />
            <Button>
              <code>[C]</code> cv
            </Button>
            <br />
            <Button>
              <code>[G]</code> github
            </Button>
          </Panel>
          <Panel>
            <PanelLegend>Projects</PanelLegend>
            <Text>
              In my own time I develop commercial and free games, release OSS,
              blog about programming and get sentimental about art, life,
              philosophy and meditation.
            </Text>
            <br />
            <Button>
              <code>[S]</code> The Song of The Fae
            </Button>
            <br />
            <Button>
              <code>[F]</code> fundamental.sh
            </Button>
            <br />
            <Button>
              <code>[V]</code> shimmeringvoid
            </Button>
            <br />
            <Button>
              <code>[P]</code> TwoPM Studios
            </Button>
          </Panel>
          <Panel>
            <PanelLegend>Generative Art</PanelLegend>
            <Button>
              <code>[G]</code> Gallery
            </Button>
            <br />
            <Button>
              <code>[H]</code> hicetnunc
            </Button>
            <br />
            <Button>
              <code>[I]</code> instagram
            </Button>
          </Panel>
          <Panel>
            <PanelLegend>Support Me</PanelLegend>
            <Button>
              <code>[E]</code> Donate ETH
            </Button>
            <br />
            <Button>
              <code>[4]</code> Donate $
            </Button>
          </Panel>
        </Interface>
      </Overlay>
      <OverlaySmall className="source-panel">
        <Interface>
          <Panel>
            <PanelLegend>View Source</PanelLegend>
            <Text>
              View the code for this site on github, it&apos;s built with
              next.js, react-three-fiber and love.
            </Text>
            <br />
            <Button>
              <code>[Q]</code> View Code
            </Button>
          </Panel>
        </Interface>
      </OverlaySmall>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
